name: ðŸš€ CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTAINER_NAME: story-stream-backend
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/story-stream-backend
  REMOTE_HOST: 188.225.46.223

jobs:
  lint:
    name: ðŸ§¹ ESLint Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3
      - name: ðŸ§± Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: ðŸ“¦ Install dependencies
        run: npm i
      - name: ðŸ” Run ESLint
        run: npm run lint

  test:
    name: ðŸ§ª Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3
      - name: ðŸ§± Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: ðŸ“¦ Install dependencies
        run: npm i
      - name: ðŸ§ª Execute tests
        run: npm test

  build:
    name: ðŸ› ï¸ Build Application
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ lint, test ]
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3
      - name: ðŸ§± Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: ðŸ“¦ Install dependencies (CI)
        run: npm i
      - name: ðŸ—ï¸ Run build
        run: npm run build
      - name: ðŸ“¤ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  docker:
    name: ðŸ³ Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ lint, test ]
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ§± Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ” Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ðŸ“¦ Read version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: ðŸ—ï¸ Build and tag Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$VERSION \
            ./

      - name: ðŸš€ Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION

  deploy_vps:
    name: ðŸš€ Deploy VPS
    runs-on: ubuntu-latest
    needs: [ docker ]
    if: github.ref == 'refs/heads/main'
    env:
      VERSION: unknown
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/story-stream-backend

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ§¾ Read version from package.json
        id: pkg
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: ðŸ” Add remote SSH host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts

      - name: ðŸ” Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ðŸ“¡ Update docker service via SSH
        run: |
          ssh admin@$REMOTE_HOST \
            "docker compose --file ~/story-stream/story-stream-docker/docker-compose.yml pull && \
            docker compose --file ~/story-stream/story-stream-docker/docker-compose.yml up --force-recreate --build -d"

  deploy_k8s:
    name: ðŸš€ Deploy k8s
    runs-on: ubuntu-latest
    needs: [ docker ]
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/story-stream-backend

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl cluster-info

      - name: ðŸ“¡ Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment backend -n story-stream
